# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate --freeze

default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

# https://pre-commit.ci/
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false

# Globally exclude files
# https://pre-commit.com/#top_level-exclude
exclude: |
  (?x)(
    .github/|
    LICENSE
  )

# pre-commit setup
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      # Identify invalid files
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml

      # git checks
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=10000
      - id: detect-private-key
      - id: check-case-conflict

      # General quality checks
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: c764d820bfc7d772ae9cc86b4696c375aee944a4  # frozen: 3.2.0
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/executablebooks/mdformat
    rev: ff29be1a1ba8029d9375882aa2c812b62112a593  # frozen: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm==0.4.1  # Mdformat plugin for GitHub Flavored Markdown compatibility » https://github.com/hukkin/mdformat-gfm/tags
          - mdformat-toc==0.3.0  # Mdformat plugin to generate a table of contents » https://github.com/hukkin/mdformat-toc/tags
          - mdformat-black==0.1.1  # Mdformat plugin to Blacken Python code blocks » https://github.com/hukkin/mdformat-black/tags
          - mdformat-shfmt==0.2.0  # Mdformat plugin to format shell code blocks » https://github.com/hukkin/mdformat-shfmt/tags
